### DISCUSSION TITLE
自动重启

### DISCUSSION THREAD

**Discussion by hupo376787** [qd-today/qd#257] [General]
机器关机后再开机，目前不会自动启动docker，加了restart也没用，请问是什么情况
```
version: "3"

services:
  qiandao:
    image: a76yyyy/qiandao:latest
    # image: a76yyyy/qiandao:lite-latest
    container_name: qiandao
    # 自动重启
    restart: always
```
