### DISCUSSION TITLE
定时任务没自动执行应该从哪里开始排查？

### DISCUSSION THREAD

**Discussion by tossp** [qd-today/qd#315] [Q&A] [answered]
使用`docker logs`看过日志没发现异常，重启容器会运行已过期过期的但没运行的任务

```yaml
version: '3'

services:
  qiandao:
    image: a76yyyy/qiandao
    container_name: "qiandao"
    depends_on:
      - redis
    volumes:
      - ./storage/config:/usr/src/app/config
    environment: 
      - ENABLE_HTTPS=True
      # - WORKER_METHOD=Batch
      - DOMAIN=********.com:2087
      - AES_KEY=********
      - COOKIE_SECRET=********
      - REDISCLOUD_URL=redis://redis:6379
      - REDIS_DB_INDEX=0
      - MAIL_DOMAIN=********
      - MAIL_SMTP=smtp.mailgun.org
      - MAIL_PORT=465
      - MAIL_USER=********
      - MAIL_PASSWORD=********
    restart: always
    ports:
      - "22008:80"
    networks:
      - ts_net  
   ```
