### ISSUE TITLE
[Feature] 更新之后数据库及配置全没了

### ISSUE THREAD

**Issue by 907739769** [qd-today/qd#312]
### Verify steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 QianDao 框架并不包含该功能特性或者还不完善
- [X] Framework 这是 QianDao 框架应包含的特性，并非模板特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

可以把SQLLITE数据库文件及配置json文件 放到宿主机目录里面，我看安装的时候有映射文件夹，但是没有起到效果，是不是docker容器打包有问题，没有把容器目录映射出来，每次重新安装容器都会导致数据库及配置全无。

### Describe the solution

可以把SQLLITE数据库文件及配置json文件 放到宿主机目录里面，我看安装的时候有映射文件夹，但是没有起到效果，是不是docker容器打包有问题，没有把容器目录映射出来，每次重新安装容器都会导致数据库及配置全无。

### Describe alternatives

可以把SQLLITE数据库文件及配置json文件 放到宿主机目录里面，我看安装的时候有映射文件夹，但是没有起到效果，是不是docker容器打包有问题，没有把容器目录映射出来，每次重新安装容器都会导致数据库及配置全无。

### Additional context

可以把SQLLITE数据库文件及配置json文件 放到宿主机目录里面，我看安装的时候有映射文件夹，但是没有起到效果，是不是docker容器打包有问题，没有把容器目录映射出来，每次重新安装容器都会导致数据库及配置全无。

**Comment by a76yyyy** [comment]
参考 
`docker run -d --name qiandao -p 8923:80 -v $(pwd)/qiandao/config:/usr/src/app/config a76yyyy/qiandao`

检查自己是否配置了 `-v $(pwd)/qiandao/config:/usr/src/app/config`

**Comment by a76yyyy** [comment]
此外可以尝试使用 `docker inspect 旧容器名` 的方式查看默认映射出去的 `/usr/src/app` 目录下的 `config` 文件夹内是否保留着旧的数据库数据 (如果没被覆盖的话)

<pre>
"Mounts": [
            {
                "Type": "volume",
                "Name": "400a6121xxxx",
                <b>"Source": "/var/lib/docker/volumes/400a6121xxxx/_data",</b>
                "Destination": "/usr/src/app",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ]
</pre>

在该目录下的`config`文件夹内找到数据库 `database.db` 文件

**Comment by 907739769** [comment]
发现多了个双引号。。。😂

```
version: "3"

services:
  qiandao:
    image: a76yyyy/qiandao:latest
    # image: a76yyyy/qiandao:lite-latest
    container_name: qiandao
    depends_on:
      - redis
    ports:
      - "1223:80"
    volumes:
      - /volume1/docker/qiandao/config:/usr/src/app/config"
    environment:
      # - QIANDAO_DEBUG=False
      # - MULTI_PROCESS=False
      # - AUTO_RELOAD=False
      # - GZIP=True
      - BIND=0.0.0.0
      - PORT=80
      - ENABLE_HTTPS=True
      # - ACCESS_LOG=True
      - DOMAIN=xxxx
      # - USE_PYCURL=True
      # - ALLOW_RETRY=True
      # - DNS_SERVER=
      # - CURL_ENCODING=True
      # - CURL_CONTENT_LENGTH=True
      # - NOT_RETRY_CODE=301|302|303|304|305|307|400|401|403|404|405|407|408|409|410|412|415|413|414|500|501|502|503|504|599
      # - EMPTY_RETRY=True
      # - COOKIE_DAY=5
      # - JAWSDB_MARIA_URL=mysql://user:pass@localhost:3306/dbname?auth_plugin=
      - REDISCLOUD_URL=redis://redis:6379
      # - TRACEBACK_PRINT=False
      # - PUSH_PIC_URL=https://fastly.jsdelivr.net/gh/a76yyyy/qiandao@master/web/static/img/push_pic.png
      # - PUSH_BATCH_SW=True
      # - DB_TYPE=sqlite3
      # - REDIS_DB_INDEX=1
      # - QIANDAO_EVIL=1000
      - PBKDF2_ITERATIONS=400
      - AES_KEY=asdasdx2sad
      - COOKIE_SECRET=dasdasd
      # - CHECK_TASK_LOOP=500
      # - DOWNLOAD_SIZE_LIMIT=5242880
      # - REQUEST_TIMEOUT=30.0
      # - CONNECT_TIMEOUT=30.0
      # - DELAY_MAX_TIMEOUT=29.9
      # - PROXIES=
      # - PROXY_DIRECT_MODE=regexp
      # - PROXY_DIRECT=(?xi)\A([a-z][a-z0-9+\-.]*://)?(0(.0){3}|127(.0){2}.1|localhost|\[::([\d]+)?\])(:[0-9]+)?
      # - EXTRA_ONNX_NAME=
      # - EXTRA_CHARSETS_NAME=
      # - NEW_TASK_DELAY=1
      - MAIL_SMTP=xxx
      - MAIL_PORT=465
      - MAIL_SSL=True
      - MAIL_USER=xxx
      - MAIL_PASSWORD=xxx
      - MAIL_FROM=xxx
      # - MAIL_DOMAIN=
      # - MAILGUN_KEY=
      # - USER0ISADMIN=True

  redis:
    image: redis:alpine
    container_name: redis
    command: ["--loglevel warning"]
    # command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      # - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - /volume1/docker/qiandao/redis/data:/data:rw
```
